# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meter.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmeter.proto\"\x9d\x06\n\x0bXMeterTelem\x12\x11\n\tTimeStamp\x18\x01 \x01(\t\x12*\n\tMeterType\x18\x02 \x01(\x0e\x32\x17.XMeterTelem.EMeterType\x12\x11\n\tPosEnergy\x18\x03 \x01(\x03\x12\x11\n\tNegEnergy\x18\x04 \x01(\x03\x12\x1b\n\x13PosActivePowerTotal\x18\x05 \x01(\x02\x12\x1b\n\x13NegActivePowerTotal\x18\x06 \x01(\x02\x12\x10\n\x08\x43urrentA\x18\x07 \x01(\x02\x12\x10\n\x08\x43urrentB\x18\x08 \x01(\x02\x12\x10\n\x08\x43urrentC\x18\t \x01(\x02\x12\x11\n\tVoltageAN\x18\n \x01(\x02\x12\x11\n\tVoltageBN\x18\x0b \x01(\x02\x12\x11\n\tVoltageCN\x18\x0c \x01(\x02\x12\x0c\n\x04\x46req\x18\r \x01(\x02\x12\x17\n\x0fPosActivePowerA\x18\x0e \x01(\x02\x12\x17\n\x0fPosActivePowerB\x18\x0f \x01(\x02\x12\x17\n\x0fPosActivePowerC\x18\x10 \x01(\x02\x12\x17\n\x0fNegActivePowerA\x18\x11 \x01(\x02\x12\x17\n\x0fNegActivePowerB\x18\x12 \x01(\x02\x12\x17\n\x0fNegActivePowerC\x18\x13 \x01(\x02\"\xdb\x02\n\nEMeterType\x12\x13\n\x0fMETER_TYPE_NONE\x10\x00\x12\x19\n\x15METER_TYPE_PRODUCTION\x10\x01\x12\x16\n\x12METER_TYPE_FEED_IN\x10\x02\x12\x1a\n\x16METER_TYPE_CONSUMPTION\x10\x03\x12\x18\n\x14METER_TYPE_PURCHASED\x10\x04\x12 \n\x1cMETER_TYPE_FEED_IN_PURCHASED\x10\x05\x12\x1f\n\x1bMETER_TYPE_SELF_CONSUMPTION\x10\x06\x12 \n\x1cMETER_TYPE_STORAGE_CHARGE_PV\x10\x07\x12 \n\x1cMETER_TYPE_STORAGE_CHARGE_AC\x10\x08\x12\x11\n\rMETER_TYPE_PV\x10\t\x12\x1d\n\x19METER_TYPE_PRODUCTION_EXT\x10\n\x12\x12\n\x0eMETER_TYPE_NUM\x10\n\x1a\x02\x10\x01')
)



_XMETERTELEM_EMETERTYPE = _descriptor.EnumDescriptor(
  name='EMeterType',
  full_name='XMeterTelem.EMeterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_PRODUCTION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_FEED_IN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_CONSUMPTION', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_PURCHASED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_FEED_IN_PURCHASED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_SELF_CONSUMPTION', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_STORAGE_CHARGE_PV', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_STORAGE_CHARGE_AC', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_PV', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_PRODUCTION_EXT', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='METER_TYPE_NUM', index=11, number=10,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=_b('\020\001'),
  serialized_start=466,
  serialized_end=813,
)
_sym_db.RegisterEnumDescriptor(_XMETERTELEM_EMETERTYPE)


_XMETERTELEM = _descriptor.Descriptor(
  name='XMeterTelem',
  full_name='XMeterTelem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TimeStamp', full_name='XMeterTelem.TimeStamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MeterType', full_name='XMeterTelem.MeterType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PosEnergy', full_name='XMeterTelem.PosEnergy', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NegEnergy', full_name='XMeterTelem.NegEnergy', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PosActivePowerTotal', full_name='XMeterTelem.PosActivePowerTotal', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NegActivePowerTotal', full_name='XMeterTelem.NegActivePowerTotal', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CurrentA', full_name='XMeterTelem.CurrentA', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CurrentB', full_name='XMeterTelem.CurrentB', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CurrentC', full_name='XMeterTelem.CurrentC', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VoltageAN', full_name='XMeterTelem.VoltageAN', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VoltageBN', full_name='XMeterTelem.VoltageBN', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VoltageCN', full_name='XMeterTelem.VoltageCN', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Freq', full_name='XMeterTelem.Freq', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PosActivePowerA', full_name='XMeterTelem.PosActivePowerA', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PosActivePowerB', full_name='XMeterTelem.PosActivePowerB', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PosActivePowerC', full_name='XMeterTelem.PosActivePowerC', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NegActivePowerA', full_name='XMeterTelem.NegActivePowerA', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NegActivePowerB', full_name='XMeterTelem.NegActivePowerB', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NegActivePowerC', full_name='XMeterTelem.NegActivePowerC', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _XMETERTELEM_EMETERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=813,
)

_XMETERTELEM.fields_by_name['MeterType'].enum_type = _XMETERTELEM_EMETERTYPE
_XMETERTELEM_EMETERTYPE.containing_type = _XMETERTELEM
DESCRIPTOR.message_types_by_name['XMeterTelem'] = _XMETERTELEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

XMeterTelem = _reflection.GeneratedProtocolMessageType('XMeterTelem', (_message.Message,), dict(
  DESCRIPTOR = _XMETERTELEM,
  __module__ = 'meter_pb2'
  # @@protoc_insertion_point(class_scope:XMeterTelem)
  ))
_sym_db.RegisterMessage(XMeterTelem)


_XMETERTELEM_EMETERTYPE._options = None
# @@protoc_insertion_point(module_scope)
